server:
  port: 8010

spring:
  application:
    name: combination
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        port: 7776
#        dashboard: 127.0.0.1:7777
  main:
    allow-circular-references: true

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,loggers,refresh'
  endpoint:
    health:
      show-details: always