apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: micro-service-server3
  labels:
    app: micro-service-server3
spec:
  ports:
    - port: 8013
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: micro-service-server3