apiVersion: v1
kind: Service
metadata:
  namespace: micro-service
  name: micro-service-server3
  labels:
    app: micro-service-server3
spec:
  ports:
    - port: 9999
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: micro-service-server3